### ISSUE TITLE
static content deploy command in readme

### ISSUE THREAD

**Issue by JensBourgeois** [Adwise/magento2-nl_NL-language#4]
Minor issue, but in the readme it says:
"php bin/magento setup:static-content:deploy nl_nl"
This should be:
"php bin/magento setup:static-content:deploy nl_NL"

Thanks!

**Comment by adwise** [comment]
Thanks for the notification. Issues will be fixed in upcoming 1.1.0 release.

**Comment by adwise** [comment]
Issues is fixed in 1.1.1
