### ISSUE TITLE
Please create a new version tag for Magento 2.1 compatibility

### ISSUE THREAD

**Issue by hostep** [Adwise/magento2-nl_NL-language#8]
Hi guys

It would be great if you can tag a new version (like 1.2.1) with the updated composer.json file, so people can actually use your module with Magento 2.1.x.

There already are some issues of people trying to upgrade to Magento 2.1 but aren't able to because of this, like:
- https://github.com/Adwise/magento2-nl_NL-language/pull/6
- https://github.com/Adwise/magento2-nl_NL-language/issues/9
- https://github.com/magento/magento2/issues/5197#issuecomment-228376834

Thanks!

**Comment by timneutkens** [comment]
@Adwise any update on this? Ticket has been open for quite a while now.

**Comment by adwise** [comment]
@hostep @timneutkens We just released a new version. Please update to version 1.2.2 to fix this problem.

**Comment by hostep** [comment]
Tnx!
