### ISSUE TITLE
Readiness Check fail while upgrading to 2.1.0

### ISSUE THREAD

**Issue by zelfkoelman** [Adwise/magento2-nl_NL-language#9]
While upgrading from Magento 2.0.7 to Magento 2.1.0 via the admin panel the following error showed up: 

> Check Component Dependency
> We found conflicting component dependencies. Hide detail
> 
> Command "update" failed: Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].
> - adwise/language-nl_nl 1.2.0 requires magento/framework 100.0.\* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
> - Can only install one of: magento/framework[100.1.0, 100.0.2].
> - Can only install one of: magento/framework[100.1.0, 100.0.3].
> - Can only install one of: magento/framework[100.1.0, 100.0.4].
> - Can only install one of: magento/framework[100.1.0, 100.0.5].
> - Can only install one of: magento/framework[100.1.0, 100.0.6].
> - Can only install one of: magento/framework[100.1.0, 100.0.7].
> - Can only install one of: magento/framework[100.1.0, 100.0.8].
> - Can only install one of: magento/framework[100.1.0, 100.0.9].
> - magento/product-community-edition 2.1.0 requires magento/framework 100.1.0 -> satisfiable by magento/framework[100.1.0].
> - Installation request for adwise/language-nl_nl ^1.2 -> satisfiable by adwise/language-nl_nl[1.2.0].
> 
> For additional assistance, see component dependency help .

The language pack was installed on June 26th using composer.

**Comment by hostep** [comment]
Hi @zelfkoelman 

The fix for this problem is already in the master branch, but @Adwise hasn't tagged a new version for this fix.

So the way to get around it, is to update your composer.json file and tell it to use the master branch instead of a version, so change your composer.json file to the following:

```
"adwise/language-nl_nl": "dev-master"
```

(branches in composer work by putting `dev-` in front of the branch name)

**Comment by adwise** [comment]
We just released 1.2.2 that will fix this issue. Please update to newest version. If you encounter any further questions please create a new issue.
